---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-db
  labels:
    name: catalog-db
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: catalog-db
    spec:
      containers:
      - name: catalog-db
        image: mysql:5.6
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          value: mysql
        - name: MYSQL_DATABASE
          value: data
          #valueFrom:
          #  secretKeyRef:
          #    name: mysql-pass
          #   key: password.txt
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
                    claimName: catalog-mysql-pv-claim
      nodeSelector:
        beta.kubernetes.io/os: linux
